PS1="\n\[\e[32m\]bash | \w | \u@\h | \D{%a %d %b %Y %H:%M:%S} \[\e[00m\] \n>> "

HISTCONTROL=ignorespace:ignoredups:erasedups
HISTSIZE=10000
HISTFILESIZE=10000

shopt -s histappend
shopt -s autocd 
shopt -s cdspell 
shopt -s direxpand
shopt -s dirspell 
shopt -s extglob extquote globstar nocaseglob 
shopt -s checkwinsize
shopt -s checkjobs
